# This file could be used for testing the API with Visual Studio Code

## Execute Log In
POST http://localhost:3001/api/sessions HTTP/1.1
content-type: application/json

{
    "username": "user.one@domain.com",
    "password": "password"
}
###

## Checking if user is still logged-in.
GET http://localhost:3001/api/sessions/current HTTP/1.1
###

## Execute Log Out.
DELETE http://localhost:3001/api/sessions/current HTTP/1.1
###

## Retrieving all the riddles (necessary to be authenticated).
GET http://localhost:3001/api/riddles HTTP/1.1
###